# This is a basic workflow to help you get started with Actions

name: Build

# Triggers the workflow on push or pull requests
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Download dependencies
        run: |
          docker pull crater44/greybel-cli
          docker tag crater44/greybel-cli:latest greybel-cli

      - name: Build all programs
        run: |
          for filename in ./src/*.src; do
            docker run -i -v "$(pwd):/app" greybel-cli greybel $filename
          done
